package com.new4s.weibao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.RowBounds;

import com.new4s.weibao.entity.Channel;

public interface ChannelMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel
	 * @mbg.generated  Wed May 16 17:25:55 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel
	 * @mbg.generated  Wed May 16 17:25:55 CST 2018
	 */
	int insert(Channel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel
	 * @mbg.generated  Wed May 16 17:25:55 CST 2018
	 */
	int insertSelective(Channel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel
	 * @mbg.generated  Wed May 16 17:25:55 CST 2018
	 */
	Channel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel
	 * @mbg.generated  Wed May 16 17:25:55 CST 2018
	 */
	int updateByPrimaryKeySelective(Channel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel
	 * @mbg.generated  Wed May 16 17:25:55 CST 2018
	 */
	int updateByPrimaryKey(Channel record);

	List<Channel> selectAll();
	
	int selectChannelCount(Map<String, Object> searchMap);

    List<Channel> selectChannelList(Map<String, Object> searchMap, RowBounds rowBounds);
}