package com.new4s.weibao.mapper;

import java.util.List;
import java.util.Map;

import com.new4s.weibao.entity.District;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbg.generated Fri May 18 15:59:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbg.generated Fri May 18 15:59:12 CST 2018
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbg.generated Fri May 18 15:59:12 CST 2018
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbg.generated Fri May 18 15:59:12 CST 2018
     */
    District selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbg.generated Fri May 18 15:59:12 CST 2018
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbg.generated Fri May 18 15:59:12 CST 2018
     */
    int updateByPrimaryKey(District record);
    
    List<District> selectByLevel(Map<String, Object> searchMap);
}