package com.new4s.weibao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.RowBounds;

import com.new4s.weibao.entity.YqOrder;
import com.new4s.weibao.entity.YqOrderVo;

public interface YqOrderMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	int insert(YqOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	int insertSelective(YqOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	YqOrder selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	int updateByPrimaryKeySelective(YqOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	int updateByPrimaryKey(YqOrder record);

	String getStatsRecord();	
	
	int getStatsRecordCount(Map<String, Object> searchMap);
	
	List<YqOrderVo> getStatsRecordList(Map<String, Object> searchMap);
	
	List<YqOrderVo> getStatsRecordList(Map<String, Object> searchMap, RowBounds rowBounds);
    
    int getYqOrderCount(Map<String, Object> searchMap);

    List<YqOrderVo> getYqOrderList(Map<String, Object> searchMap, RowBounds rowBounds);
    
    List<YqOrderVo> getYqOrderList(Map<String, Object> searchMap);
}