package com.new4s.weibao.dao.mapper;

import com.new4s.weibao.dao.entity.Channel;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    Channel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    int updateByPrimaryKey(Channel record);
}