package com.new4s.weibao.dao.mapper;

import com.new4s.weibao.dao.entity.SearchRecord;

public interface SearchRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue May 08 11:31:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue May 08 11:31:15 CST 2018
     */
    int insert(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue May 08 11:31:15 CST 2018
     */
    int insertSelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue May 08 11:31:15 CST 2018
     */
    SearchRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue May 08 11:31:15 CST 2018
     */
    int updateByPrimaryKeySelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Tue May 08 11:31:15 CST 2018
     */
    int updateByPrimaryKey(SearchRecord record);
}