package com.new4s.weibao.dao.mapper;

import com.new4s.weibao.dao.entity.YqOrder;

public interface YqOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Fri May 18 09:21:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Fri May 18 09:21:24 CST 2018
	 */
	int insert(YqOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Fri May 18 09:21:24 CST 2018
	 */
	int insertSelective(YqOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Fri May 18 09:21:24 CST 2018
	 */
	YqOrder selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Fri May 18 09:21:24 CST 2018
	 */
	int updateByPrimaryKeySelective(YqOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yq_order
	 * @mbg.generated  Fri May 18 09:21:24 CST 2018
	 */
	int updateByPrimaryKey(YqOrder record);
}