package com.new4s.weibao.dao.mapper;

import com.new4s.weibao.dao.entity.YqQuery;
import com.new4s.weibao.dao.entity.YqQueryWithBLOBs;

public interface YqQueryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yq_query
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yq_query
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    int insert(YqQueryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yq_query
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    int insertSelective(YqQueryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yq_query
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    YqQueryWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yq_query
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    int updateByPrimaryKeySelective(YqQueryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yq_query
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(YqQueryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yq_query
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    int updateByPrimaryKey(YqQuery record);
    
    YqQueryWithBLOBs selectByVin(String vin);
}