package com.new4s.weibao.dao.entity;

import java.util.Date;

public class Channel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.id
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_name
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.appsecret
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    private String appsecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.valid_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    private Date validTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.callback_url
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    private String callbackUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.create_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.update_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.id
     *
     * @return the value of channel.id
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.id
     *
     * @param id the value for channel.id
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_name
     *
     * @return the value of channel.channel_name
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_name
     *
     * @param channelName the value for channel.channel_name
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.appsecret
     *
     * @return the value of channel.appsecret
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.appsecret
     *
     * @param appsecret the value for channel.appsecret
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.valid_time
     *
     * @return the value of channel.valid_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public Date getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.valid_time
     *
     * @param validTime the value for channel.valid_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.callback_url
     *
     * @return the value of channel.callback_url
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.callback_url
     *
     * @param callbackUrl the value for channel.callback_url
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.create_time
     *
     * @return the value of channel.create_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.create_time
     *
     * @param createTime the value for channel.create_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.update_time
     *
     * @return the value of channel.update_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.update_time
     *
     * @param updateTime the value for channel.update_time
     *
     * @mbg.generated Wed May 09 14:20:51 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}