package com.new4s.weibao.dao.entity;

import java.util.Date;

public class TaskRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_record.id
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_record.vin_code
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	private String vinCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_record.channel_id
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_record.appsecret
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	private String appsecret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_record.status
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_record.create_time
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_record.update_time
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_record.id
	 * @return  the value of task_record.id
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_record.id
	 * @param id  the value for task_record.id
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_record.vin_code
	 * @return  the value of task_record.vin_code
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public String getVinCode() {
		return vinCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_record.vin_code
	 * @param vinCode  the value for task_record.vin_code
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public void setVinCode(String vinCode) {
		this.vinCode = vinCode == null ? null : vinCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_record.channel_id
	 * @return  the value of task_record.channel_id
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_record.channel_id
	 * @param channelId  the value for task_record.channel_id
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_record.appsecret
	 * @return  the value of task_record.appsecret
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public String getAppsecret() {
		return appsecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_record.appsecret
	 * @param appsecret  the value for task_record.appsecret
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public void setAppsecret(String appsecret) {
		this.appsecret = appsecret == null ? null : appsecret.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_record.status
	 * @return  the value of task_record.status
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_record.status
	 * @param status  the value for task_record.status
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_record.create_time
	 * @return  the value of task_record.create_time
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_record.create_time
	 * @param createTime  the value for task_record.create_time
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_record.update_time
	 * @return  the value of task_record.update_time
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_record.update_time
	 * @param updateTime  the value for task_record.update_time
	 * @mbg.generated  Tue May 08 11:31:15 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}