package com.new4s.weibao.dao.entity;

public class YqQuery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.brand_id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.img_url
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.malfunction_num
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer malfunctionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.km
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String km;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.complete_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.brand_name
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.last_info_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String lastInfoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.admin_name
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.engine
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String engine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.vin_code
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String vinCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.right_brand
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String rightBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.structure_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String structureStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.engine_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String engineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.kilm_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String kilmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.is_water_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String isWaterStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.is_fire_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String isFireStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.safety_bag_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String safetyBagStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.is_new_img
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer isNewImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.vin_change_admin_id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer vinChangeAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.vin_change_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer vinChangeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.is_auto
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Byte isAuto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.is_urgent
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Byte isUrgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.robot
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private Integer robot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.token
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.transmission_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String transmissionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.channel_type
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String channelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.license_plate
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String licensePlate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.id
     *
     * @return the value of yq_query.id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.id
     *
     * @param id the value for yq_query.id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.brand_id
     *
     * @return the value of yq_query.brand_id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.brand_id
     *
     * @param brandId the value for yq_query.brand_id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.img_url
     *
     * @return the value of yq_query.img_url
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.img_url
     *
     * @param imgUrl the value for yq_query.img_url
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.malfunction_num
     *
     * @return the value of yq_query.malfunction_num
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getMalfunctionNum() {
        return malfunctionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.malfunction_num
     *
     * @param malfunctionNum the value for yq_query.malfunction_num
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setMalfunctionNum(Integer malfunctionNum) {
        this.malfunctionNum = malfunctionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.km
     *
     * @return the value of yq_query.km
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getKm() {
        return km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.km
     *
     * @param km the value for yq_query.km
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setKm(String km) {
        this.km = km == null ? null : km.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.complete_time
     *
     * @return the value of yq_query.complete_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.complete_time
     *
     * @param completeTime the value for yq_query.complete_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setCompleteTime(Integer completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.brand_name
     *
     * @return the value of yq_query.brand_name
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.brand_name
     *
     * @param brandName the value for yq_query.brand_name
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.last_info_time
     *
     * @return the value of yq_query.last_info_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getLastInfoTime() {
        return lastInfoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.last_info_time
     *
     * @param lastInfoTime the value for yq_query.last_info_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setLastInfoTime(String lastInfoTime) {
        this.lastInfoTime = lastInfoTime == null ? null : lastInfoTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.admin_name
     *
     * @return the value of yq_query.admin_name
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.admin_name
     *
     * @param adminName the value for yq_query.admin_name
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.engine
     *
     * @return the value of yq_query.engine
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.engine
     *
     * @param engine the value for yq_query.engine
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.vin_code
     *
     * @return the value of yq_query.vin_code
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getVinCode() {
        return vinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.vin_code
     *
     * @param vinCode the value for yq_query.vin_code
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setVinCode(String vinCode) {
        this.vinCode = vinCode == null ? null : vinCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.right_brand
     *
     * @return the value of yq_query.right_brand
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getRightBrand() {
        return rightBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.right_brand
     *
     * @param rightBrand the value for yq_query.right_brand
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setRightBrand(String rightBrand) {
        this.rightBrand = rightBrand == null ? null : rightBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.structure_status
     *
     * @return the value of yq_query.structure_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getStructureStatus() {
        return structureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.structure_status
     *
     * @param structureStatus the value for yq_query.structure_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setStructureStatus(String structureStatus) {
        this.structureStatus = structureStatus == null ? null : structureStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.engine_status
     *
     * @return the value of yq_query.engine_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getEngineStatus() {
        return engineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.engine_status
     *
     * @param engineStatus the value for yq_query.engine_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setEngineStatus(String engineStatus) {
        this.engineStatus = engineStatus == null ? null : engineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.kilm_status
     *
     * @return the value of yq_query.kilm_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getKilmStatus() {
        return kilmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.kilm_status
     *
     * @param kilmStatus the value for yq_query.kilm_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setKilmStatus(String kilmStatus) {
        this.kilmStatus = kilmStatus == null ? null : kilmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.is_water_status
     *
     * @return the value of yq_query.is_water_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getIsWaterStatus() {
        return isWaterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.is_water_status
     *
     * @param isWaterStatus the value for yq_query.is_water_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setIsWaterStatus(String isWaterStatus) {
        this.isWaterStatus = isWaterStatus == null ? null : isWaterStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.is_fire_status
     *
     * @return the value of yq_query.is_fire_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getIsFireStatus() {
        return isFireStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.is_fire_status
     *
     * @param isFireStatus the value for yq_query.is_fire_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setIsFireStatus(String isFireStatus) {
        this.isFireStatus = isFireStatus == null ? null : isFireStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.safety_bag_status
     *
     * @return the value of yq_query.safety_bag_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getSafetyBagStatus() {
        return safetyBagStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.safety_bag_status
     *
     * @param safetyBagStatus the value for yq_query.safety_bag_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setSafetyBagStatus(String safetyBagStatus) {
        this.safetyBagStatus = safetyBagStatus == null ? null : safetyBagStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.is_new_img
     *
     * @return the value of yq_query.is_new_img
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getIsNewImg() {
        return isNewImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.is_new_img
     *
     * @param isNewImg the value for yq_query.is_new_img
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setIsNewImg(Integer isNewImg) {
        this.isNewImg = isNewImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.vin_change_admin_id
     *
     * @return the value of yq_query.vin_change_admin_id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getVinChangeAdminId() {
        return vinChangeAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.vin_change_admin_id
     *
     * @param vinChangeAdminId the value for yq_query.vin_change_admin_id
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setVinChangeAdminId(Integer vinChangeAdminId) {
        this.vinChangeAdminId = vinChangeAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.vin_change_time
     *
     * @return the value of yq_query.vin_change_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getVinChangeTime() {
        return vinChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.vin_change_time
     *
     * @param vinChangeTime the value for yq_query.vin_change_time
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setVinChangeTime(Integer vinChangeTime) {
        this.vinChangeTime = vinChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.is_auto
     *
     * @return the value of yq_query.is_auto
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Byte getIsAuto() {
        return isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.is_auto
     *
     * @param isAuto the value for yq_query.is_auto
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setIsAuto(Byte isAuto) {
        this.isAuto = isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.is_urgent
     *
     * @return the value of yq_query.is_urgent
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Byte getIsUrgent() {
        return isUrgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.is_urgent
     *
     * @param isUrgent the value for yq_query.is_urgent
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setIsUrgent(Byte isUrgent) {
        this.isUrgent = isUrgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.robot
     *
     * @return the value of yq_query.robot
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public Integer getRobot() {
        return robot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.robot
     *
     * @param robot the value for yq_query.robot
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setRobot(Integer robot) {
        this.robot = robot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.token
     *
     * @return the value of yq_query.token
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.token
     *
     * @param token the value for yq_query.token
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.transmission_status
     *
     * @return the value of yq_query.transmission_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getTransmissionStatus() {
        return transmissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.transmission_status
     *
     * @param transmissionStatus the value for yq_query.transmission_status
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setTransmissionStatus(String transmissionStatus) {
        this.transmissionStatus = transmissionStatus == null ? null : transmissionStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.channel_type
     *
     * @return the value of yq_query.channel_type
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.channel_type
     *
     * @param channelType the value for yq_query.channel_type
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.license_plate
     *
     * @return the value of yq_query.license_plate
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getLicensePlate() {
        return licensePlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.license_plate
     *
     * @param licensePlate the value for yq_query.license_plate
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate == null ? null : licensePlate.trim();
    }
}