package com.new4s.weibao.dao.entity;

public class YqQueryWithBLOBs extends YqQuery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.explain
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.query_img
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String queryImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.processed_text_contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String processedTextContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.text_contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String textContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String contents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.explain_text
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String explainText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.kilm_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String kilmJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.structure_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String structureJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.engine_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String engineJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.safety_bag_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String safetyBagJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.ps_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String psJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.hs_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String hsJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.bsx_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String bsxJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yq_query.callbackurl
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    private String callbackurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.explain
     *
     * @return the value of yq_query.explain
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.explain
     *
     * @param explain the value for yq_query.explain
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.query_img
     *
     * @return the value of yq_query.query_img
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getQueryImg() {
        return queryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.query_img
     *
     * @param queryImg the value for yq_query.query_img
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setQueryImg(String queryImg) {
        this.queryImg = queryImg == null ? null : queryImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.processed_text_contents
     *
     * @return the value of yq_query.processed_text_contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getProcessedTextContents() {
        return processedTextContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.processed_text_contents
     *
     * @param processedTextContents the value for yq_query.processed_text_contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setProcessedTextContents(String processedTextContents) {
        this.processedTextContents = processedTextContents == null ? null : processedTextContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.text_contents
     *
     * @return the value of yq_query.text_contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getTextContents() {
        return textContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.text_contents
     *
     * @param textContents the value for yq_query.text_contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setTextContents(String textContents) {
        this.textContents = textContents == null ? null : textContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.contents
     *
     * @return the value of yq_query.contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.contents
     *
     * @param contents the value for yq_query.contents
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.explain_text
     *
     * @return the value of yq_query.explain_text
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getExplainText() {
        return explainText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.explain_text
     *
     * @param explainText the value for yq_query.explain_text
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setExplainText(String explainText) {
        this.explainText = explainText == null ? null : explainText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.kilm_json
     *
     * @return the value of yq_query.kilm_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getKilmJson() {
        return kilmJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.kilm_json
     *
     * @param kilmJson the value for yq_query.kilm_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setKilmJson(String kilmJson) {
        this.kilmJson = kilmJson == null ? null : kilmJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.structure_json
     *
     * @return the value of yq_query.structure_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getStructureJson() {
        return structureJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.structure_json
     *
     * @param structureJson the value for yq_query.structure_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setStructureJson(String structureJson) {
        this.structureJson = structureJson == null ? null : structureJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.engine_json
     *
     * @return the value of yq_query.engine_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getEngineJson() {
        return engineJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.engine_json
     *
     * @param engineJson the value for yq_query.engine_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setEngineJson(String engineJson) {
        this.engineJson = engineJson == null ? null : engineJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.safety_bag_json
     *
     * @return the value of yq_query.safety_bag_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getSafetyBagJson() {
        return safetyBagJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.safety_bag_json
     *
     * @param safetyBagJson the value for yq_query.safety_bag_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setSafetyBagJson(String safetyBagJson) {
        this.safetyBagJson = safetyBagJson == null ? null : safetyBagJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.ps_json
     *
     * @return the value of yq_query.ps_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getPsJson() {
        return psJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.ps_json
     *
     * @param psJson the value for yq_query.ps_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setPsJson(String psJson) {
        this.psJson = psJson == null ? null : psJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.hs_json
     *
     * @return the value of yq_query.hs_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getHsJson() {
        return hsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.hs_json
     *
     * @param hsJson the value for yq_query.hs_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setHsJson(String hsJson) {
        this.hsJson = hsJson == null ? null : hsJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.bsx_json
     *
     * @return the value of yq_query.bsx_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getBsxJson() {
        return bsxJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.bsx_json
     *
     * @param bsxJson the value for yq_query.bsx_json
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setBsxJson(String bsxJson) {
        this.bsxJson = bsxJson == null ? null : bsxJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yq_query.callbackurl
     *
     * @return the value of yq_query.callbackurl
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public String getCallbackurl() {
        return callbackurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yq_query.callbackurl
     *
     * @param callbackurl the value for yq_query.callbackurl
     *
     * @mbg.generated Mon May 07 16:19:57 CST 2018
     */
    public void setCallbackurl(String callbackurl) {
        this.callbackurl = callbackurl == null ? null : callbackurl.trim();
    }
}