package com.new4s.weibao.entity;

import java.util.Date;

public class BrandInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_info.id
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_info.brand
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_info.create_time
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_info.update_time
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_info.id
     *
     * @return the value of brand_info.id
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_info.id
     *
     * @param id the value for brand_info.id
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_info.brand
     *
     * @return the value of brand_info.brand
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_info.brand
     *
     * @param brand the value for brand_info.brand
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_info.create_time
     *
     * @return the value of brand_info.create_time
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_info.create_time
     *
     * @param createTime the value for brand_info.create_time
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_info.update_time
     *
     * @return the value of brand_info.update_time
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_info.update_time
     *
     * @param updateTime the value for brand_info.update_time
     *
     * @mbg.generated Thu May 17 14:31:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}