package com.new4s.weibao.entity;

import java.util.Date;

public class Channel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.id
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.channel_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String channelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.province
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.province_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String provinceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.city
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.city_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.appsecret
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String appsecret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.contacts
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String contacts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.mobile
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.address
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.valid_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private Date validTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.callback_url
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private String callbackUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.create_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column channel.update_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.id
	 * @return  the value of channel.id
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.id
	 * @param id  the value for channel.id
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.channel_name
	 * @return  the value of channel.channel_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.channel_name
	 * @param channelName  the value for channel.channel_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName == null ? null : channelName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.province
	 * @return  the value of channel.province
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.province
	 * @param province  the value for channel.province
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.province_name
	 * @return  the value of channel.province_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getProvinceName() {
		return provinceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.province_name
	 * @param provinceName  the value for channel.province_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName == null ? null : provinceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.city
	 * @return  the value of channel.city
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.city
	 * @param city  the value for channel.city
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.city_name
	 * @return  the value of channel.city_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.city_name
	 * @param cityName  the value for channel.city_name
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.appsecret
	 * @return  the value of channel.appsecret
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getAppsecret() {
		return appsecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.appsecret
	 * @param appsecret  the value for channel.appsecret
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setAppsecret(String appsecret) {
		this.appsecret = appsecret == null ? null : appsecret.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.contacts
	 * @return  the value of channel.contacts
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getContacts() {
		return contacts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.contacts
	 * @param contacts  the value for channel.contacts
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setContacts(String contacts) {
		this.contacts = contacts == null ? null : contacts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.mobile
	 * @return  the value of channel.mobile
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.mobile
	 * @param mobile  the value for channel.mobile
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.address
	 * @return  the value of channel.address
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.address
	 * @param address  the value for channel.address
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.valid_time
	 * @return  the value of channel.valid_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public Date getValidTime() {
		return validTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.valid_time
	 * @param validTime  the value for channel.valid_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setValidTime(Date validTime) {
		this.validTime = validTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.callback_url
	 * @return  the value of channel.callback_url
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public String getCallbackUrl() {
		return callbackUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.callback_url
	 * @param callbackUrl  the value for channel.callback_url
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.create_time
	 * @return  the value of channel.create_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.create_time
	 * @param createTime  the value for channel.create_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column channel.update_time
	 * @return  the value of channel.update_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column channel.update_time
	 * @param updateTime  the value for channel.update_time
	 * @mbg.generated  Fri May 18 16:23:10 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}