package com.new4s.weibao.entity;

import java.util.Date;

public class YqOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.channel_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.order_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.vin
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private String vin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.brand_name
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.dealer_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private Integer dealerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.status
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private Long time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.create_time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yq_order.update_time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.id
	 * @return  the value of yq_order.id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.id
	 * @param id  the value for yq_order.id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.channel_id
	 * @return  the value of yq_order.channel_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.channel_id
	 * @param channelId  the value for yq_order.channel_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.order_id
	 * @return  the value of yq_order.order_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.order_id
	 * @param orderId  the value for yq_order.order_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.vin
	 * @return  the value of yq_order.vin
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public String getVin() {
		return vin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.vin
	 * @param vin  the value for yq_order.vin
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setVin(String vin) {
		this.vin = vin == null ? null : vin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.brand_name
	 * @return  the value of yq_order.brand_name
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.brand_name
	 * @param brandName  the value for yq_order.brand_name
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName == null ? null : brandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.dealer_id
	 * @return  the value of yq_order.dealer_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public Integer getDealerId() {
		return dealerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.dealer_id
	 * @param dealerId  the value for yq_order.dealer_id
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setDealerId(Integer dealerId) {
		this.dealerId = dealerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.status
	 * @return  the value of yq_order.status
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.status
	 * @param status  the value for yq_order.status
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.time
	 * @return  the value of yq_order.time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public Long getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.time
	 * @param time  the value for yq_order.time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setTime(Long time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.create_time
	 * @return  the value of yq_order.create_time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.create_time
	 * @param createTime  the value for yq_order.create_time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yq_order.update_time
	 * @return  the value of yq_order.update_time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yq_order.update_time
	 * @param updateTime  the value for yq_order.update_time
	 * @mbg.generated  Thu May 17 11:14:29 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}